[target.thumbv7em-none-eabi]
runner = "probe-run --chip STM32WLE5JCIx --connect-under-reset"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabi"
